using UnityEngine;

/// <summary>
/// Launches firework rockets at random intervals. Recreates the Brackeys VFX Graph fireworks
/// with the built-in Particle System (Quest friendly):
///   Rockets (this system) --Birth--> Rocket Trail
///                         --Death--> Explosion --Birth--> Explosion Trail
///                         --Death--> Flash
/// Generated by Tools > SkillVerse > Fireworks (FireworksBuilder).
/// </summary>
[RequireComponent(typeof(ParticleSystem))]
public class FireworkLauncher : MonoBehaviour
{
    [Header("Timing")]
    public bool autoPlay = true;
    [Tooltip("Random delay (seconds) before the first launch.")]
    public Vector2 startDelay = new Vector2(0f, 4f);
    [Tooltip("Random time (seconds) between launches.")]
    public Vector2 interval = new Vector2(2.5f, 6f);
    public Vector2Int rocketsPerLaunch = new Vector2Int(1, 2);

    [Header("Explosion colours")]
    public Color flashColor = Color.white;
    public Color burstStartColor = new Color(0.2f, 1f, 1f);
    public Color burstEndColor = new Color(0.8f, 0.3f, 1f);

    [Header("References")]
    [SerializeField] private ParticleSystem explosion;
    [SerializeField] private ParticleSystem flash;

    private ParticleSystem rockets;
    private float nextLaunch;

    private void Awake()
    {
        rockets = GetComponent<ParticleSystem>();
        ApplyColours();
    }

    private void OnEnable()
    {
        nextLaunch = Time.time + Random.Range(startDelay.x, startDelay.y);
    }

    private void Update()
    {
        if (!autoPlay || Time.time < nextLaunch) return;

        Launch();
        nextLaunch = Time.time + Random.Range(interval.x, interval.y);
    }

    [ContextMenu("Launch")]
    public void Launch()
    {
        if (rockets == null) rockets = GetComponent<ParticleSystem>();
        rockets.Emit(Random.Range(rocketsPerLaunch.x, rocketsPerLaunch.y + 1));
    }

    /// <summary>Pushes the colour fields into the explosion and flash gradients.</summary>
    public void ApplyColours()
    {
        if (explosion != null)
        {
            var gradient = new Gradient();
            gradient.SetKeys(
                new[]
                {
                    new GradientColorKey(flashColor, 0f),
                    new GradientColorKey(burstStartColor, 0.06f),
                    new GradientColorKey(burstEndColor, 1f)
                },
                new[]
                {
                    new GradientAlphaKey(1f, 0f),
                    new GradientAlphaKey(1f, 0.35f),
                    new GradientAlphaKey(0f, 1f)
                });
            var col = explosion.colorOverLifetime;
            col.enabled = true;
            col.color = new ParticleSystem.MinMaxGradient(gradient);
        }

        if (flash != null)
        {
            var gradient = new Gradient();
            gradient.SetKeys(
                new[] { new GradientColorKey(Color.Lerp(flashColor, burstStartColor, 0.5f), 0f), new GradientColorKey(burstStartColor, 1f) },
                new[] { new GradientAlphaKey(0.45f, 0f), new GradientAlphaKey(0f, 1f) });
            var col = flash.colorOverLifetime;
            col.enabled = true;
            col.color = new ParticleSystem.MinMaxGradient(gradient);
        }
    }

    public void SetReferences(ParticleSystem explosionSystem, ParticleSystem flashSystem)
    {
        explosion = explosionSystem;
        flash = flashSystem;
    }
}
